<?php

namespace Tests\Feature;

use App\Column;
use App\Dashboard;
use App\DashboardUser;
use App\User;
use Illuminate\Database\Query\Builder;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class ColumnTest extends TestCase
{

    use DatabaseMigrations;

    private $user;


    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->seed();

        $this->user = User::find(2);
    }


    /**
     * @return void
     */
    public function test_create_successful_column_in_dashboard()
    {
        $form_data = [
            'title'        => 'some title',
            'dashboard_id' => Dashboard::where('owner_id', $this->user->id)->first()->id
        ];

        $this->actingAs($this->user, 'api')
            ->postJson(route('columns.store'), $form_data)
            ->assertCreated()
            ->assertSee($form_data['title']);
    }


    /**
     * @return void
     */
    public function testUserCanNotCreateNewColumn()
    {
        $form_data = [
            'title'        => 'some title',
            'dashboard_id' => 2
        ];

        $this->actingAs($this->user, 'api')
            ->postJson(route('columns.store'), $form_data)
            ->assertForbidden();
    }


    /**
     * @return void
     */
    public function testUserCanUpdateNewColumn()
    {
        $column = Column::whereIn('dashboard_id', function ($query) {
            return $this->getDashboardIDForUser($query);
        })->first();

        $form_data = [
            'title'        => 'some title',
            'dashboard_id' => $column->dashboard_id,
            'sort'         => 11
        ];

        $query_params = ['column' => $column->dashboard_id];

        $this->actingAs($this->user, 'api')
            ->putJson(route('columns.update', $query_params), $form_data)
            ->assertStatus(200)
            ->assertSee($form_data['title']);
    }


    /**
     * @return void
     */
    public function testUserCanNotUpdateNewColumn()
    {
        $column = Column::whereNotIn('dashboard_id', function ($query) {
            return $this->getDashboardIDForUser($query);
        })->first();

        $form_data = [
            'title'        => 'some title',
            'dashboard_id' => $column->id,
            'sort'         => 11
        ];

        $query_params = ['column' => $column->id];

        $this->actingAs($this->user, 'api')
            ->putJson(route('columns.update', $query_params), $form_data)
            ->assertForbidden();
    }


    public function testUserCanDeleteColumn()
    {
        $dashboard = Dashboard::where('owner_id', $this->user->id)->first();
        $column = Column::where('dashboard_id', $dashboard->id)->first();


        $this->actingAs($this->user, 'api')
            ->deleteJson(route('columns.destroy', compact('column')))
            ->assertStatus(200);
    }


    /**
     * @return void
     */
    public function testUserCanNotDeleteColumn()
    {
        $column = Column::whereNotIn('dashboard_id', function ($query) {
            return $this->getDashboardIDForUser($query);
        })->first();

        $query_params = ['column' => $column->id];

        $this->actingAs($this->user, 'api')
            ->deleteJson(route('columns.destroy', $query_params))
            ->assertForbidden();
    }


    public function testUpdateSortOfColumns()
    {
        $dashboard = Dashboard::where('owner_id', $this->user->id)->first();
        $columns = Column::where('dashboard_id', $dashboard->id)
            ->get()
            ->pluck('id');

        $query_params = ['dashboard' => $dashboard->id];

        $form_data = ['set' => $columns];

        $this->actingAs($this->user, 'api')
            ->postJson(route('columns.sort', $query_params), $form_data)
            ->assertStatus(200);

        collect($columns)->each(function ($id, $index) {
            $column = Column::find($id);

            $this->assertEquals($index, $column->sort);
        });

    }


    /**
     * @param Builder $query
     *
     * @return Builder
     */
    private function getDashboardIDForUser(Builder $query): Builder
    {
        return $query->select('dashboard_id')
            ->from((new DashboardUser)->getTable())
            ->where('user_id', $this->user->id);
    }
}
