<?php

namespace Tests\Feature;

use App\User;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class DashboardTest extends TestCase
{
    use DatabaseMigrations;

    private $user;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->seed();

        $this->user = User::find(2);

        $this->withoutExceptionHandling();
    }


    /**
     * For user with id=2 count of dashboards is 4
     *
     * @return void
     */
    public function testUsersDashboards()
    {
        $response = $this->actingAs($this->user, 'api')
            ->getJson(route('dashboards.index'));

        $response
            ->assertStatus(200)
            ->assertJsonCount(4);
    }
}
