<?php

namespace Tests\Feature;

use App\Dashboard;
use App\Services\DashboardService;
use App\User;
use Illuminate\Http\UploadedFile;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Illuminate\Support\Facades\Storage;
use Tests\TestCase;

class DashboardTest extends TestCase
{

    use DatabaseMigrations;

    private $user;


    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->seed();

        $this->user = User::find(2);
    }


    /**
     * For user with id=2 count of dashboards is 4
     *
     * @return void
     */
    public function testUsersDashboards()
    {
        $this->actingAs($this->user, 'api')
            ->getJson(route('dashboards.index'))
            ->assertStatus(200)
            ->assertJsonCount(4);
    }


    /**
     * For user with id=2 count of dashboards is 4
     *
     * @return void
     */
    public function test_user_can_load_content_of_dashboard()
    {
        $dashboard = DashboardService::getUserDashboards($this->user)->first();

        $query_params = ['dashboard' => $dashboard->id];

        $this->actingAs($this->user, 'api')
            ->getJson(route('dashboards.show', $query_params))
            ->assertStatus(200)
            ->assertJsonCount(count($dashboard->columns));
    }


    /**
     * Test successful store Dashboard with background
     */
    public function testStoreSuccessfulDashboard()
    {
        Storage::fake('public');

        $file = UploadedFile::fake()->image('avatar.jpg')->size(200);
        $filePath = sprintf('backgrounds/%s', $file->hashName());

        $form_data = [
            'title'      => 'some title',
            'background' => $file
        ];

        $response = $this->actingAs($this->user, 'api')
            ->postJson(route('dashboards.store'), $form_data)
            ->assertCreated()
            ->assertSee($form_data['title'])
            ->assertSee(str_replace('/', '\/', $filePath));

        Storage::disk('public')->assertExists($filePath);

        $dashboard = Dashboard::find($response['id']);

        $this->assertEquals('/storage/' . $filePath, $dashboard->background);
    }


    /**
     * Test failed store Dashboard with background
     */
    public function testStoreFailedDashboard()
    {
        Storage::fake('public');

        $file = UploadedFile::fake()->image('avatar.jpg')->size(4096);

        $form_data = [
            //'title' => 'some title',
            'background' => $file
        ];

        $this->actingAs($this->user, 'api')
            ->postJson(route('dashboards.store'), $form_data)
            ->assertJsonStructure([
                'message',
                'errors' => ['title', 'background']
            ]);
    }


    /**
     * Test successful update Dashboard
     */
    public function testUpdateSuccessDashboard()
    {
        $user = User::find(1);

        Storage::fake('public');

        $file = UploadedFile::fake()->image('avatar.jpg')->size(200);
        $filePath = sprintf('backgrounds/%s', $file->hashName());

        $form_data = [
            'title'      => 'another title',
            'background' => $file
        ];

        $query_params = ['dashboard' => 1];

        $response = $this->actingAs($user, 'api')
            ->putJson(route('dashboards.update', $query_params), $form_data)
            ->assertStatus(200)
            ->assertSee($form_data['title'])
            ->assertSee(str_replace('/', '\/', $filePath));

        $this->assertCount(3, $user->dashboards);

        Storage::disk('public')->assertExists($filePath);

        $dashboard = Dashboard::find($response['id']);

        $this->assertEquals('/storage/' . $filePath, $dashboard->background);
    }


    /**
     * test user can not update dashboard
     */
    public function testUserCanNotUpdateDashboard()
    {
        Storage::fake('public');

        $dashboard = Dashboard::where('owner_id', '<>', $this->user->id)->first();
        $file = UploadedFile::fake()->image('avatar.jpg')->size(200);

        $form_data = [
            'title'      => 'another title',
            'background' => $file
        ];

        $query_params = ['dashboard' => $dashboard->id];

        $this->actingAs($this->user, 'api')
            ->putJson(route('dashboards.update', $query_params), $form_data)
            ->assertForbidden();
    }


    public function testUserCanNotViewDashboard()
    {
        $dashboard = Dashboard::find(2);

        $query_params = ['dashboard' => $dashboard->id];

        $this->actingAs($this->user, 'api')
            ->getJson(route('dashboards.show', $query_params))
            ->assertForbidden();
    }


    public function testSuccessfulDeleteDashboard()
    {
        $dashboard = Dashboard::where('owner_id', $this->user->id)->first();

        $this->actingAs($this->user, 'api')
            ->deleteJson(route('dashboards.destroy', ['dashboard' => $dashboard->id]))
            ->assertStatus(200);

        $this->assertEquals(false, Dashboard::where('id', $dashboard->id)->exists());
    }


    public function testUserCanNotDeleteDashboard()
    {
        $dashboard = Dashboard::where('owner_id', '<>', $this->user->id)->first();

        $query_params = ['dashboard' => $dashboard->id];

        $this->actingAs($this->user, 'api')
            ->deleteJson(route('dashboards.destroy', $query_params))
            ->assertForbidden();
    }
}

